# Three peer aware Power Servers

eureka:
  client:
    service-url:
      defaultZone: http://peer1:5001/eureka,http://peer2:5002/eureka,http://peer3:5003/eureka
spring:
  application:
    name: power

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
server:
  port: 6001


---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
server:
  port: 6002


---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
server:
  port: 6003

